// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class TChatStdRoom
{
    public int FId { get; set; }

    public int? FStudentId { get; set; }

    public int? FRoomId { get; set; }

    public int? FState { get; set; }

    public virtual TChatRoom FRoom { get; set; }
}