// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class TChatContent
{
    public int FContentId { get; set; }

    public int? FRole { get; set; }

    public int? FSendId { get; set; }

    public int? FRoomId { get; set; }

    public int? FDateId { get; set; }

    public string FContent { get; set; }

    public DateTime? FSendTime { get; set; }

    public int? FType { get; set; }

    public string FOther { get; set; }

    public virtual TChatDate FDate { get; set; }

    public virtual T會員老師 FSend { get; set; }
}