// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class TChatDate
{
    public int FDateId { get; set; }

    public DateTime? FDate { get; set; }

    public virtual ICollection<TChatContent> TChatContents { get; set; } = new List<TChatContent>();
}