// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class TChatRoom
{
    public int FRoomId { get; set; }

    public string FRoomCode { get; set; }

    public string FGroup { get; set; }

    public string FRoomName { get; set; }

    public byte[] FRoomImage { get; set; }

    public int? FTeacherId { get; set; }

    public int? FAuthority { get; set; }

    public int? FHidden { get; set; }

    public DateTime? FCreatTime { get; set; }

    public DateTime? FOpenTime { get; set; }

    public virtual T會員老師 FTeacher { get; set; }

    public virtual ICollection<TChatStdRoom> TChatStdRooms { get; set; } = new List<TChatStdRoom>();
}