// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class TQuizPaper
{
    public int FId { get; set; }

    public int? FQuizId { get; set; }

    public int? FQuestionId { get; set; }

    public int? FNum { get; set; }

    public virtual TQuizQuestion FQuestion { get; set; }

    public virtual TQuizQuiz FQuiz { get; set; }
}