// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class TQuizRecord
{
    public int FRecordId { get; set; }

    public int FQuizId { get; set; }

    public int? FStudentId { get; set; }

    public string FGroup { get; set; }

    public int? FState { get; set; }

    public string FStartTime { get; set; }

    public string FEndTime { get; set; }

    public decimal? FRate { get; set; }

    public virtual TQuizQuiz FQuiz { get; set; }

    public virtual T會員學生 FStudent { get; set; }
}