// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T公告分類
{
    public int 分類id { get; set; }

    public string 名稱 { get; set; }

    public virtual ICollection<T公告本體> T公告本體s { get; set; } = new List<T公告本體>();
}