// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T工作履歷資料
{
    public int FId { get; set; }

    public int F學員Id { get; set; }

    public string F履歷名稱 { get; set; }

    public string F履歷狀態 { get; set; }

    public string F專長技能 { get; set; }

    public string F語文能力 { get; set; }

    public string F有無工作經驗 { get; set; }

    public string F工作性質 { get; set; }

    public string F工作時段 { get; set; }

    public string F配合輪班 { get; set; }

    public string F希望職稱 { get; set; }

    public string F希望薪水待遇 { get; set; }

    public string F希望工作地點 { get; set; }

    public string F自傳 { get; set; }

    public DateTime? F建立時間 { get; set; }

    public DateTime? F最後更新時間 { get; set; }

    public string F刪除狀態 { get; set; }

    public string F刪除或關閉原因 { get; set; }

    public virtual T會員學生 F學員 { get; set; }

    public virtual ICollection<T工作履歷表工作經驗> T工作履歷表工作經驗s { get; set; } = new List<T工作履歷表工作經驗>();
}