// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T工作應徵工作紀錄
{
    public int FId { get; set; }

    public int F學員Id { get; set; }

    public int F職缺Id { get; set; }

    public string F履歷版本內容 { get; set; }

    public int F通知總表Id { get; set; }

    public DateTime F應徵時間 { get; set; }

    public string F刪除狀態 { get; set; }

    public virtual T會員學生 F學員 { get; set; }

    public virtual T工作職缺資料 F職缺 { get; set; }

    public virtual T通知通知訊息總表 F通知總表 { get; set; }
}