// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T工作工作經驗
{
    public int FId { get; set; }

    public int F學員Id { get; set; }

    public string F公司名稱 { get; set; }

    public string F職務名稱 { get; set; }

    public string F起始年月 { get; set; }

    public string F結束年月 { get; set; }

    public string F薪水待遇 { get; set; }

    public string F工作內容 { get; set; }

    public virtual T會員學生 F學員 { get; set; }

    public virtual ICollection<T工作履歷表工作經驗> T工作履歷表工作經驗s { get; set; } = new List<T工作履歷表工作經驗>();
}