// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T工作公司資料
{
    public int FId { get; set; }

    public string F統一編號 { get; set; }

    public string F公司名稱 { get; set; }

    public string F帳號 { get; set; }

    public string F密碼 { get; set; }

    public string F帳號狀態 { get; set; }

    public string F聯絡人 { get; set; }

    public string F聯絡人電話 { get; set; }

    public string F聯絡人Email { get; set; }

    public string F負責人 { get; set; }

    public string F公司電話 { get; set; }

    public string F公司地址 { get; set; }

    public string F公司簡介 { get; set; }

    public DateTime? F註冊時間 { get; set; }

    public DateTime? F審核通過時間 { get; set; }

    public DateTime? F最後更新時間 { get; set; }

    public string F刪除狀態 { get; set; }

    public virtual ICollection<T工作職缺資料> T工作職缺資料s { get; set; } = new List<T工作職缺資料>();

    public virtual ICollection<T通知公司通知> T通知公司通知s { get; set; } = new List<T通知公司通知>();
}