// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T工作職缺資料
{
    public int FId { get; set; }

    public string F職務名稱 { get; set; }

    public string F職缺狀態 { get; set; }

    public int F公司Id { get; set; }

    public string F薪水待遇 { get; set; }

    public string F工作性質 { get; set; }

    public string F工作地點 { get; set; }

    public string F工作時段 { get; set; }

    public string F輪班需求 { get; set; }

    public int? F需求人數 { get; set; }

    public string F工作內容 { get; set; }

    public string F學歷要求 { get; set; }

    public string F語文條件 { get; set; }

    public string F工作技能 { get; set; }

    public string F其他條件 { get; set; }

    public DateTime? F建立時間 { get; set; }

    public DateTime? F最後更新時間 { get; set; }

    public string F刪除狀態 { get; set; }

    public string F刪除或關閉原因 { get; set; }

    public virtual T工作公司資料 F公司 { get; set; }

    public virtual ICollection<T工作儲存工作紀錄> T工作儲存工作紀錄s { get; set; } = new List<T工作儲存工作紀錄>();

    public virtual ICollection<T工作應徵工作紀錄> T工作應徵工作紀錄s { get; set; } = new List<T工作應徵工作紀錄>();
}