// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T影片ShoppingCart
{
    public int Id { get; set; }

    public int FStudentId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual T會員學生 FStudent { get; set; }

    public virtual ICollection<T影片CartDetail> T影片CartDetails { get; set; } = new List<T影片CartDetail>();
}