// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T影片問題單表
{
    public int FId { get; set; }

    public string FDate { get; set; }

    public int FStudentId { get; set; }

    public int FTeacherId { get; set; }

    public string FSubject { get; set; }

    public string FProgress { get; set; }

    public int? FParentId { get; set; }

    public string FType { get; set; }

    public int FSeqNo { get; set; }

    public virtual T影片OrderDetail FSeqNoNavigation { get; set; }

    public virtual T會員學生 FStudent { get; set; }

    public virtual T會員老師 FTeacher { get; set; }
}