// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T影片Video
{
    public int FVideoId { get; set; }

    public string FVideoTitle { get; set; }

    public string FUrl { get; set; }

    public int 科目id { get; set; }

    public decimal FPrice { get; set; }

    public string FImagePath { get; set; }

    public virtual ICollection<T影片OrderDetail> T影片OrderDetails { get; set; } = new List<T影片OrderDetail>();

    public virtual ICollection<T影片Tag中繼表> T影片Tag中繼表s { get; set; } = new List<T影片Tag中繼表>();

    public virtual T課程科目 科目 { get; set; }
}