// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T影片Tag表
{
    public int FTagId { get; set; }

    public string FTag { get; set; }

    public virtual ICollection<T影片Tag中繼表> T影片Tag中繼表s { get; set; } = new List<T影片Tag中繼表>();
}