// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T影片OrderStatus
{
    public int Id { get; set; }

    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual T影片Order IdNavigation { get; set; }
}