// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T影片Order
{
    public int FOrderId { get; set; }

    public int FStudentId { get; set; }

    public DateTime FDate { get; set; }

    public virtual T會員學生 FStudent { get; set; }

    public virtual ICollection<T影片OrderDetail> T影片OrderDetails { get; set; } = new List<T影片OrderDetail>();
}