// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T會員學生登入紀錄
{
    public int 學生登入紀錄id { get; set; }

    public int 學生id { get; set; }

    public DateTime 登入時間 { get; set; }

    public string 狀態 { get; set; }

    public virtual T會員學生 學生 { get; set; }
}