// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T會員老師登入紀錄
{
    public int 老師登入紀錄id { get; set; }

    public int 老師id { get; set; }

    public DateTime 登入時間 { get; set; }

    public string 狀態 { get; set; }

    public virtual T會員老師 老師 { get; set; }
}