// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T會員老師
{
    public int 老師id { get; set; }

    public string 姓名 { get; set; }

    public string 性別 { get; set; }

    public string 身分證字號 { get; set; }

    public string 信箱 { get; set; }

    public string 手機 { get; set; }

    public string 地址 { get; set; }

    public string 密碼 { get; set; }

    public byte[] 圖片 { get; set; }

    public DateTime? 生日 { get; set; }

    public DateTime 註冊日期 { get; set; }

    public DateTime 修改日期 { get; set; }

    public string 狀態 { get; set; }

    public string 鎖定 { get; set; }

    public string 其他登入 { get; set; }

    public string 學校 { get; set; }

    public string 科系 { get; set; }

    public string 學位 { get; set; }

    public string 畢肄 { get; set; }

    public string Salt { get; set; }

    public string Token { get; set; }

    public virtual ICollection<T公告本體> T公告本體s { get; set; } = new List<T公告本體>();

    public virtual ICollection<T影片問題單表> T影片問題單表s { get; set; } = new List<T影片問題單表>();

    public virtual ICollection<T會員老師登入紀錄> T會員老師登入紀錄s { get; set; } = new List<T會員老師登入紀錄>();

    public virtual ICollection<T考試考試總表> T考試考試總表s { get; set; } = new List<T考試考試總表>();

    public virtual ICollection<T考試試題總表> T考試試題總表s { get; set; } = new List<T考試試題總表>();

    public virtual ICollection<T課程班級> T課程班級s { get; set; } = new List<T課程班級>();

    public virtual ICollection<T課程班級科目> T課程班級科目s { get; set; } = new List<T課程班級科目>();

    public virtual ICollection<T課程老師科目> T課程老師科目s { get; set; } = new List<T課程老師科目>();

    public virtual ICollection<T通知老師通知> T通知老師通知s { get; set; } = new List<T通知老師通知>();
}