// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T會員學生
{
    public int 學生id { get; set; }

    public string 姓名 { get; set; }

    public string 性別 { get; set; }

    public string 身分證字號 { get; set; }

    public string 信箱 { get; set; }

    public string 手機 { get; set; }

    public string 地址 { get; set; }

    public string 密碼 { get; set; }

    public byte[] 圖片 { get; set; }

    public DateTime? 生日 { get; set; }

    public DateTime? 註冊日期 { get; set; }

    public DateTime? 修改日期 { get; set; }

    public string 狀態 { get; set; }

    public string 鎖定 { get; set; }

    public string 其他登入 { get; set; }

    public string 學校 { get; set; }

    public string 科系 { get; set; }

    public string 學位 { get; set; }

    public string 畢肄 { get; set; }

    public string Salt { get; set; }

    public string Token { get; set; }

    public virtual ICollection<TQuizRecord> TQuizRecords { get; set; } = new List<TQuizRecord>();

    public virtual ICollection<T工作儲存工作紀錄> T工作儲存工作紀錄s { get; set; } = new List<T工作儲存工作紀錄>();

    public virtual ICollection<T工作履歷資料> T工作履歷資料s { get; set; } = new List<T工作履歷資料>();

    public virtual ICollection<T工作工作經驗> T工作工作經驗s { get; set; } = new List<T工作工作經驗>();

    public virtual ICollection<T工作應徵工作紀錄> T工作應徵工作紀錄s { get; set; } = new List<T工作應徵工作紀錄>();

    public virtual ICollection<T工作推薦職缺> T工作推薦職缺s { get; set; } = new List<T工作推薦職缺>();

    public virtual ICollection<T影片Order> T影片Orders { get; set; } = new List<T影片Order>();

    public virtual ICollection<T影片ShoppingCart> T影片ShoppingCarts { get; set; } = new List<T影片ShoppingCart>();

    public virtual ICollection<T影片問題單表> T影片問題單表s { get; set; } = new List<T影片問題單表>();

    public virtual ICollection<T會員出勤> T會員出勤s { get; set; } = new List<T會員出勤>();

    public virtual ICollection<T會員學生登入紀錄> T會員學生登入紀錄s { get; set; } = new List<T會員學生登入紀錄>();

    public virtual ICollection<T訂餐學員口味表> T訂餐學員口味表s { get; set; } = new List<T訂餐學員口味表>();

    public virtual ICollection<T訂餐學員最愛商家表> T訂餐學員最愛商家表s { get; set; } = new List<T訂餐學員最愛商家表>();

    public virtual ICollection<T訂餐訂單資訊表> T訂餐訂單資訊表s { get; set; } = new List<T訂餐訂單資訊表>();

    public virtual ICollection<T訂餐購物車> T訂餐購物車s { get; set; } = new List<T訂餐購物車>();

    public virtual ICollection<T討論文章> T討論文章s { get; set; } = new List<T討論文章>();

    public virtual ICollection<T討論文章點讚> T討論文章點讚s { get; set; } = new List<T討論文章點讚>();

    public virtual ICollection<T討論留言> T討論留言s { get; set; } = new List<T討論留言>();

    public virtual ICollection<T討論留言點讚> T討論留言點讚s { get; set; } = new List<T討論留言點讚>();

    public virtual ICollection<T課程學生班級> T課程學生班級s { get; set; } = new List<T課程學生班級>();

    public virtual ICollection<T課程評分主表> T課程評分主表s { get; set; } = new List<T課程評分主表>();
}