// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T考試試題總表
{
    public int 試卷id { get; set; }

    public string 備註 { get; set; }

    public int? 科目id { get; set; }

    public int? 老師id { get; set; }

    public string 試題 { get; set; }

    public string 答案 { get; set; }

    public int? 試卷題數 { get; set; }

    public DateTime? 創建時間 { get; set; }

    public DateTime? 更新時間 { get; set; }

    public bool? 共享 { get; set; }

    public virtual ICollection<T考試考試總表> T考試考試總表s { get; set; } = new List<T考試考試總表>();

    public virtual T課程科目 科目 { get; set; }

    public virtual T會員老師 老師 { get; set; }
}