// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T訂餐學員最愛商家表
{
    public int 識別碼id { get; set; }

    public int 學員id { get; set; }

    public int 店家id { get; set; }

    public virtual T會員學生 學員 { get; set; }

    public virtual T訂餐店家資料表 店家 { get; set; }
}