// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T訂餐菜單
{
    public int 菜單id { get; set; }

    public string 菜單名稱 { get; set; }

    public int? 餐點id { get; set; }

    public int? 營業時間表id { get; set; }

    public virtual T訂餐營業時間表 營業時間表 { get; set; }

    public virtual T訂餐餐點資訊表 餐點 { get; set; }
}