// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T訂餐口味總表
{
    public int 口味id { get; set; }

    public string 風味名稱 { get; set; }

    public virtual ICollection<T訂餐學員口味表> T訂餐學員口味表s { get; set; } = new List<T訂餐學員口味表>();

    public virtual ICollection<T訂餐店家風味表> T訂餐店家風味表s { get; set; } = new List<T訂餐店家風味表>();
}