// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T訂餐訂單詳細資訊表
{
    public int 訂單詳細表id { get; set; }

    public int 訂單id { get; set; }

    public int 店家id { get; set; }

    public int 餐點id { get; set; }

    public int? 餐點數量 { get; set; }

    public decimal? 金額小記 { get; set; }

    public virtual T訂餐店家資料表 店家 { get; set; }

    public virtual T訂餐訂單資訊表 訂單 { get; set; }

    public virtual T訂餐餐點資訊表 餐點 { get; set; }
}