// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T訂餐店家資料表
{
    public int 店家id { get; set; }

    public string 店家名稱 { get; set; }

    public string 地址 { get; set; }

    public string 電話 { get; set; }

    public string 餐廳介紹 { get; set; }

    public string 餐廳照片 { get; set; }

    public string 電子信箱 { get; set; }

    public string 密碼 { get; set; }

    public virtual ICollection<T訂餐學員最愛商家表> T訂餐學員最愛商家表s { get; set; } = new List<T訂餐學員最愛商家表>();

    public virtual ICollection<T訂餐店家風味表> T訂餐店家風味表s { get; set; } = new List<T訂餐店家風味表>();

    public virtual ICollection<T訂餐營業時間表> T訂餐營業時間表s { get; set; } = new List<T訂餐營業時間表>();

    public virtual ICollection<T訂餐訂單詳細資訊表> T訂餐訂單詳細資訊表s { get; set; } = new List<T訂餐訂單詳細資訊表>();

    public virtual ICollection<T訂餐餐點資訊表> T訂餐餐點資訊表s { get; set; } = new List<T訂餐餐點資訊表>();
}