// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T訂餐店家風味表
{
    public int 識別碼id { get; set; }

    public int 店家id { get; set; }

    public int 口味id { get; set; }

    public virtual T訂餐口味總表 口味 { get; set; }

    public virtual T訂餐店家資料表 店家 { get; set; }
}