// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T訂餐評論表
{
    public int 評論表id { get; set; }

    public int 訂單id { get; set; }

    public string 評論 { get; set; }

    public string 滿意度星數 { get; set; }

    public virtual T訂餐訂單資訊表 訂單 { get; set; }
}