// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T討論看板
{
    public int 看板id { get; set; }

    public string 名稱 { get; set; }

    public string 封面圖 { get; set; }

    public virtual ICollection<T討論子版> T討論子版s { get; set; } = new List<T討論子版>();

    public virtual ICollection<T討論文章> T討論文章s { get; set; } = new List<T討論文章>();

    public virtual ICollection<T討論留言> T討論留言s { get; set; } = new List<T討論留言>();
}