// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T討論文章點讚
{
    public int? 學生id { get; set; }

    public int? 文章id { get; set; }

    public string 讚or倒讚 { get; set; }

    public int Id { get; set; }

    public virtual T會員學生 學生 { get; set; }

    public virtual T討論文章 文章 { get; set; }
}