// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T課程學生班級
{
    public int 學生班級id { get; set; }

    public int 學生id { get; set; }

    public int 班級id { get; set; }

    public int 狀態 { get; set; }

    public virtual T會員學生 學生 { get; set; }

    public virtual T課程班級 班級 { get; set; }
}