// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T課程班級
{
    public int 班級id { get; set; }

    public string 班級名稱 { get; set; }

    public int 班級導師id { get; set; }

    public DateTime 入學日期 { get; set; }

    public DateTime 結訓日期 { get; set; }

    public int 狀態 { get; set; }

    public virtual ICollection<T會員出勤> T會員出勤s { get; set; } = new List<T會員出勤>();

    public virtual ICollection<T課程學生班級> T課程學生班級s { get; set; } = new List<T課程學生班級>();

    public virtual ICollection<T課程班級科目> T課程班級科目s { get; set; } = new List<T課程班級科目>();

    public virtual T會員老師 班級導師 { get; set; }
}