// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T課程科目分類
{
    public int 科目類別id { get; set; }

    public string 科目類別名稱 { get; set; }

    public string 科目類別封面 { get; set; }

    public int 狀態 { get; set; }

    public virtual ICollection<T課程科目> T課程科目s { get; set; } = new List<T課程科目>();
}