// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T課程課程
{
    public int 課程id { get; set; }

    public int 班級科目id { get; set; }

    public DateTime 開始時間 { get; set; }

    public DateTime 結束時間 { get; set; }

    public string 課堂摘要 { get; set; }

    public int? 值日生id { get; set; }

    public int 狀態 { get; set; }

    public virtual T會員學生 值日生 { get; set; }

    public virtual T課程班級科目 班級科目 { get; set; }
}