// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T課程班級科目
{
    public int 班級科目id { get; set; }

    public int 班級id { get; set; }

    public int 科目id { get; set; }

    public int 老師id { get; set; }

    public int 狀態 { get; set; }

    public virtual ICollection<T考試考試總表> T考試考試總表s { get; set; } = new List<T考試考試總表>();

    public virtual ICollection<T課程評分主表> T課程評分主表s { get; set; } = new List<T課程評分主表>();

    public virtual ICollection<T課程課程> T課程課程s { get; set; } = new List<T課程課程>();

    public virtual T課程班級 班級 { get; set; }

    public virtual T課程科目 科目 { get; set; }

    public virtual T會員老師 老師 { get; set; }
}