// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T課程評分
{
    public int 評分id { get; set; }

    public int 評分主表id { get; set; }

    public string 評分分類 { get; set; }

    public string 評分題目 { get; set; }

    public int 評分 { get; set; }

    public int 狀態 { get; set; }

    public virtual T課程評分主表 評分主表 { get; set; }
}