// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T課程老師科目
{
    public int 老師科目id { get; set; }

    public int 老師id { get; set; }

    public int 科目id { get; set; }

    public int 狀態 { get; set; }

    public virtual T課程科目 科目 { get; set; }

    public virtual T會員老師 老師 { get; set; }
}