// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T課程科目
{
    public int 科目id { get; set; }

    public string 科目名稱 { get; set; }

    public int 科目類別id { get; set; }

    public int 狀態 { get; set; }

    public virtual ICollection<T影片Video> T影片Videos { get; set; } = new List<T影片Video>();

    public virtual ICollection<T考試試題總表> T考試試題總表s { get; set; } = new List<T考試試題總表>();

    public virtual ICollection<T課程班級科目> T課程班級科目s { get; set; } = new List<T課程班級科目>();

    public virtual ICollection<T課程老師科目> T課程老師科目s { get; set; } = new List<T課程老師科目>();

    public virtual T課程科目分類 科目類別 { get; set; }
}