// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T課程評分主表
{
    public int 評分主表id { get; set; }

    public int 班級科目id { get; set; }

    public int 學生id { get; set; }

    public DateTime 提交時間 { get; set; }

    public int 狀態 { get; set; }

    public string 改進意見 { get; set; }

    public virtual ICollection<T課程評分> T課程評分s { get; set; } = new List<T課程評分>();

    public virtual T會員學生 學生 { get; set; }

    public virtual T課程班級科目 班級科目 { get; set; }
}