// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T通知通知訊息總表
{
    public int FId { get; set; }

    public string F發送者類型 { get; set; }

    public string F接收者類型 { get; set; }

    public string F訊息類別 { get; set; }

    public string F內容 { get; set; }

    public DateTime? F發送時間 { get; set; }

    public int? F父訊息Id { get; set; }

    public string F刪除狀態 { get; set; }

    public virtual T通知通知訊息總表 F父訊息 { get; set; }

    public virtual ICollection<T通知通知訊息總表> InverseF父訊息 { get; set; } = new List<T通知通知訊息總表>();

    public virtual ICollection<T工作應徵工作紀錄> T工作應徵工作紀錄s { get; set; } = new List<T工作應徵工作紀錄>();

    public virtual ICollection<T通知公司通知> T通知公司通知s { get; set; } = new List<T通知公司通知>();

    public virtual ICollection<T通知學生通知> T通知學生通知s { get; set; } = new List<T通知學生通知>();

    public virtual ICollection<T通知老師通知> T通知老師通知s { get; set; } = new List<T通知老師通知>();
}