// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Class_system_Backstage_pj.Models;

public partial class T通知老師通知
{
    public int FId { get; set; }

    public int F老師Id { get; set; }

    public int F通知總表Id { get; set; }

    public virtual T會員老師 F老師 { get; set; }

    public virtual T通知通知訊息總表 F通知總表 { get; set; }
}